-- ═══════════════════════════════════════════════════════════════
-- SPATIAL OPERATING SYSTEM — Migration 001 (v2)
-- Creates the 3-layer location system + spatial stock links
-- Includes: soft deletes, z-index ordering, auto-label triggers
-- Run in: Supabase SQL Editor
-- Date: 2026-03-09
-- ═══════════════════════════════════════════════════════════════

-- ─── Layer 1: Storage Places (Buildings/Stores) ──────────────

CREATE TABLE IF NOT EXISTS storage_places (
  id bigserial PRIMARY KEY,
  firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,
  place_name text NOT NULL,            -- "KT Shop", "Godown B"
  place_slug text NOT NULL,            -- "KT", "GDB" — short label for auto-labels
  place_type text NOT NULL DEFAULT 'shop',  -- 'shop' | 'warehouse' | 'godown'
  floor_count int NOT NULL DEFAULT 1,
  top_view_image_url text,             -- optional photo/sketch of the building
  notes text,
  deleted_at timestamptz,              -- soft delete (NULL = active)
  created_at timestamptz DEFAULT now(),
  UNIQUE(firm_id, place_slug)
);

-- ─── Layer 2: Zones (Named regions within a floor) ───────────
-- polygon_coords stores [[x,y], [x,y], ...] for Three.js rendering.

CREATE TABLE IF NOT EXISTS storage_zones (
  id bigserial PRIMARY KEY,
  firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,
  place_id bigint NOT NULL REFERENCES storage_places(id) ON DELETE RESTRICT,
  floor_num int NOT NULL DEFAULT 0,         -- 0 = ground floor
  zone_name text NOT NULL,                  -- "Back Staircase Corner"
  zone_slug text NOT NULL,                  -- "BSC"
  zone_label text,                          -- auto-generated by trigger: "KT-F0-BSC"
  polygon_coords jsonb,                     -- [[x,y],[x,y],...] for Three.js
  zone_color text DEFAULT '#4f46e5',        -- hex color for 3D highlight
  notes text,
  deleted_at timestamptz,                   -- soft delete
  UNIQUE(place_id, floor_num, zone_slug)
);

-- ─── Layer 3: Slots (Named spots within a zone) ─────────────

CREATE TABLE IF NOT EXISTS storage_slots (
  id bigserial PRIMARY KEY,
  firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,
  zone_id bigint NOT NULL REFERENCES storage_zones(id) ON DELETE RESTRICT,
  slot_name text NOT NULL,                  -- "Stack A"
  slot_label text,                          -- auto-generated by trigger: "KT-F0-BSC-STACK_A"
  order_index int DEFAULT 0,               -- z-level: 0 = floor, 1 = on top, 2 = above that
  capacity_parcels int,                     -- NULL = unknown/chaotic
  notes text,
  deleted_at timestamptz                    -- soft delete
);

-- ─── Stock ↔ Slot Assignment ─────────────────────────────────

CREATE TABLE IF NOT EXISTS item_locations (
  id bigserial PRIMARY KEY,
  firm_id uuid NOT NULL REFERENCES firms(id) ON DELETE CASCADE,
  item_id bigint NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  slot_id bigint NOT NULL REFERENCES storage_slots(id) ON DELETE RESTRICT,
  parcel_count int NOT NULL DEFAULT 0,
  is_primary boolean DEFAULT false,
  packaging_type text,                      -- "gunny bag", "brown box medium", "carry bag"
  packaging_tags text[] DEFAULT '{}',       -- {"fragile", "seasonal", "holi"}
  last_verified_at timestamptz,
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz,                   -- soft delete
  UNIQUE(item_id, slot_id)
);

-- ═══════════════════════════════════════════════════════════════
-- AUTO-LABEL TRIGGERS
-- Ensures zone_label and slot_label stay accurate even on rename.
-- ═══════════════════════════════════════════════════════════════

-- Trigger: auto-generate zone_label = "PLACE_SLUG-F{floor}-ZONE_SLUG"
CREATE OR REPLACE FUNCTION generate_zone_label()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  p_slug text;
BEGIN
  SELECT place_slug INTO p_slug
  FROM storage_places WHERE id = NEW.place_id;

  NEW.zone_label := p_slug || '-F' || NEW.floor_num || '-' || NEW.zone_slug;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_zone_label
  BEFORE INSERT OR UPDATE OF zone_slug, floor_num, place_id
  ON storage_zones
  FOR EACH ROW
  EXECUTE FUNCTION generate_zone_label();

-- Trigger: auto-generate slot_label = "ZONE_LABEL-SLOT_NAME_UPPER"
CREATE OR REPLACE FUNCTION generate_slot_label()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  z_label text;
BEGIN
  SELECT zone_label INTO z_label
  FROM storage_zones WHERE id = NEW.zone_id;

  NEW.slot_label := z_label || '-' || UPPER(REPLACE(NEW.slot_name, ' ', '_'));
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_slot_label
  BEFORE INSERT OR UPDATE OF slot_name, zone_id
  ON storage_slots
  FOR EACH ROW
  EXECUTE FUNCTION generate_slot_label();

-- Cascade label updates: when a zone_slug or place_slug changes,
-- re-fire slot labels by touching all child slots.
CREATE OR REPLACE FUNCTION cascade_zone_label_to_slots()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF OLD.zone_label IS DISTINCT FROM NEW.zone_label THEN
    UPDATE storage_slots
    SET slot_name = slot_name  -- no-op update triggers trg_slot_label
    WHERE zone_id = NEW.id AND deleted_at IS NULL;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cascade_zone_to_slots
  AFTER UPDATE OF zone_label
  ON storage_zones
  FOR EACH ROW
  EXECUTE FUNCTION cascade_zone_label_to_slots();

-- ═══════════════════════════════════════════════════════════════
-- RLS POLICIES
-- ═══════════════════════════════════════════════════════════════

ALTER TABLE storage_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE storage_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE item_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "firm_isolation" ON storage_places USING (firm_id = get_my_firm_id());
CREATE POLICY "firm_isolation" ON storage_zones USING (firm_id = get_my_firm_id());
CREATE POLICY "firm_isolation" ON storage_slots USING (firm_id = get_my_firm_id());
CREATE POLICY "firm_isolation" ON item_locations USING (firm_id = get_my_firm_id());

-- ═══════════════════════════════════════════════════════════════
-- PERFORMANCE INDEXES
-- ═══════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_storage_zones_place
  ON storage_zones(place_id, floor_num) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_storage_slots_zone
  ON storage_slots(zone_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_item_locations_item
  ON item_locations(item_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_item_locations_slot
  ON item_locations(slot_id) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_storage_slots_order
  ON storage_slots(zone_id, order_index) WHERE deleted_at IS NULL;

-- ═══════════════════════════════════════════════════════════════
-- HELPER VIEW: Item → Full Location Path
-- Excludes soft-deleted records. For search: "WHERE is item X?"
-- ═══════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW item_location_full AS
SELECT
  il.id,
  il.firm_id,
  il.item_id,
  i.item_name,
  il.slot_id,
  ss.slot_name,
  ss.slot_label,
  ss.order_index,
  il.parcel_count,
  il.is_primary,
  il.packaging_type,
  il.packaging_tags,
  sz.id AS zone_id,
  sz.zone_name,
  sz.zone_label,
  sz.floor_num,
  sz.polygon_coords,
  sz.zone_color,
  sp.id AS place_id,
  sp.place_name,
  sp.place_slug,
  sp.place_type
FROM item_locations il
JOIN storage_slots ss ON ss.id = il.slot_id     AND ss.deleted_at IS NULL
JOIN storage_zones sz ON sz.id = ss.zone_id     AND sz.deleted_at IS NULL
JOIN storage_places sp ON sp.id = sz.place_id   AND sp.deleted_at IS NULL
JOIN items i ON i.id = il.item_id
WHERE il.deleted_at IS NULL;
