/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 warehousef1-front-mesh.glb --types --keepnames --meta 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Custom Rectangle.003Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Wall: THREE.Mesh
    Wall001: THREE.Mesh
    Wall002: THREE.Mesh
    Wall003: THREE.Mesh
    rightright1002: THREE.Mesh
    leftleft: THREE.Mesh
    leftleft001: THREE.Mesh
    leftperpback: THREE.Mesh
    leftperpback001: THREE.Mesh
    leftright: THREE.Mesh
    leftright001: THREE.Mesh
    rightleft: THREE.Mesh
    rightleft001: THREE.Mesh
    rightperpfront: THREE.Mesh
    rightperpfront001: THREE.Mesh
    rightright1: THREE.Mesh
    rightright1001: THREE.Mesh
    rightright2: THREE.Mesh
    rightright2001: THREE.Mesh
    rightright3: THREE.Mesh
    Wall004: THREE.Mesh
    Wall005: THREE.Mesh
    Wall006: THREE.Mesh
    Floor003: THREE.Mesh
    Wall007: THREE.Mesh
    Wall008: THREE.Mesh
    Wall009: THREE.Mesh
    Wall010: THREE.Mesh
    Wall011: THREE.Mesh
    Wall012: THREE.Mesh
    Wall013: THREE.Mesh
    Wall014: THREE.Mesh
    Floor001: THREE.Mesh
    Wall015: THREE.Mesh
    Wall016: THREE.Mesh
    Wall017: THREE.Mesh
    Wall018: THREE.Mesh
    Wall019: THREE.Mesh
    Wall020: THREE.Mesh
    Wall021: THREE.Mesh
    Wall022: THREE.Mesh
    Floor002: THREE.Mesh
    Wall023: THREE.Mesh
    Wall024: THREE.Mesh
    Wall025: THREE.Mesh
    Wall026: THREE.Mesh
    Wall027: THREE.Mesh
    Wall028: THREE.Mesh
    Wall029: THREE.Mesh
    Wall030: THREE.Mesh
    Floor004: THREE.Mesh
    Wall031: THREE.Mesh
  }
  materials: {
    ['Custom Rectangle_Mat.012']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/warehousef1-front-mesh.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Room_1">
        <mesh name="Wall" geometry={nodes.Wall.geometry} material={nodes.Wall.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall' }}>
          <group name="obj_x" position={[4.648, 0, 0]} userData={{ name: 'obj_x' }} />
        </mesh>
        <mesh name="Wall001" geometry={nodes.Wall001.geometry} material={nodes.Wall001.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.001' }}>
          <group name="obj_x001" position={[6.096, 0, 0]} userData={{ name: 'obj_x.001' }} />
        </mesh>
        <mesh name="Wall002" geometry={nodes.Wall002.geometry} material={nodes.Wall002.material} position={[-2.083, 0, -4.496]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Wall.002' }}>
          <group name="obj_x002" position={[9.246, 0, 0]} userData={{ name: 'obj_x.002' }} />
        </mesh>
        <mesh name="Wall003" geometry={nodes.Wall003.geometry} material={nodes.Wall003.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.003' }}>
          <mesh name="rightright1002" geometry={nodes.rightright1002.geometry} material={materials['Custom Rectangle_Mat.012']} position={[5.626, 0, 8.151]} rotation={[0, -1.568, 0]} scale={[0.758, 1, 3]} userData={{ name: 'rightright1.002' }} />
          <mesh name="leftleft" geometry={nodes.leftleft.geometry} material={materials['Custom Rectangle_Mat.012']} position={[0.459, 0, 2.441]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'leftleft' }} />
          <mesh name="leftleft001" geometry={nodes.leftleft001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[0.459, 0, 2.441]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'leftleft.001' }} />
          <mesh name="leftperpback" geometry={nodes.leftperpback.geometry} material={materials['Custom Rectangle_Mat.012']} position={[1.524, 0, 0.457]} rotation={[Math.PI, 0, Math.PI]} scale={[0.998, 1, 3]} userData={{ name: 'leftperpback' }} />
          <mesh name="leftperpback001" geometry={nodes.leftperpback001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[1.524, 0, 0.457]} rotation={[Math.PI, 0, Math.PI]} scale={[0.998, 1, 3]} userData={{ name: 'leftperpback.001' }} />
          <mesh name="leftright" geometry={nodes.leftright.geometry} material={materials['Custom Rectangle_Mat.012']} position={[2.619, 0, 2.427]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'leftright' }} />
          <mesh name="leftright001" geometry={nodes.leftright001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[8.179, 0, 4.496]} userData={{ name: 'leftright.001' }} />
          <mesh name="rightleft" geometry={nodes.rightleft.geometry} material={materials['Custom Rectangle_Mat.012']} position={[3.523, 0, 2.427]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'rightleft' }} />
          <mesh name="rightleft001" geometry={nodes.rightleft001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[3.523, 0, 2.427]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'rightleft.001' }} />
          <mesh name="rightperpfront" geometry={nodes.rightperpfront.geometry} material={materials['Custom Rectangle_Mat.012']} position={[4.564, 0, 8.835]} rotation={[Math.PI, 0, Math.PI]} scale={[0.998, 1, 3]} userData={{ name: 'rightperpfront' }} />
          <mesh name="rightperpfront001" geometry={nodes.rightperpfront001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[4.564, 0, 8.835]} rotation={[Math.PI, 0, Math.PI]} scale={[0.998, 1, 3]} userData={{ name: 'rightperpfront.001' }} />
          <mesh name="rightright1" geometry={nodes.rightright1.geometry} material={materials['Custom Rectangle_Mat.012']} position={[5.645, 0, 2.445]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'rightright1' }} />
          <mesh name="rightright1001" geometry={nodes.rightright1001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[5.645, 0, 2.445]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'rightright1.001' }} />
          <mesh name="rightright2" geometry={nodes.rightright2.geometry} material={materials['Custom Rectangle_Mat.012']} position={[5.636, 0, 5.474]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'rightright2' }} />
          <mesh name="rightright2001" geometry={nodes.rightright2001.geometry} material={materials['Custom Rectangle_Mat.012']} position={[5.636, 0, 5.474]} rotation={[0, -1.568, 0]} scale={[0.998, 1, 3]} userData={{ name: 'rightright2.001' }} />
          <mesh name="rightright3" geometry={nodes.rightright3.geometry} material={materials['Custom Rectangle_Mat.012']} position={[5.626, 0, 8.151]} rotation={[0, -1.568, 0]} scale={[0.758, 1, 3]} userData={{ name: 'rightright3' }} />
        </mesh>
        <mesh name="Wall004" geometry={nodes.Wall004.geometry} material={nodes.Wall004.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.004' }}>
          <group name="obj_x003" position={[4.648, 0, 0]} userData={{ name: 'obj_x.003' }} />
        </mesh>
        <mesh name="Wall005" geometry={nodes.Wall005.geometry} material={nodes.Wall005.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.005' }} />
        <mesh name="Wall006" geometry={nodes.Wall006.geometry} material={nodes.Wall006.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.006' }}>
          <group name="obj_x004" position={[4.648, 0, 0]} userData={{ name: 'obj_x.004' }} />
        </mesh>
        <mesh name="Floor003" geometry={nodes.Floor003.geometry} material={materials['Material.001']} userData={{ name: 'Floor.003' }} />
        <mesh name="Wall007" geometry={nodes.Wall007.geometry} material={nodes.Wall007.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.007' }} />
        <mesh name="Wall008" geometry={nodes.Wall008.geometry} material={nodes.Wall008.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.008' }} />
        <mesh name="Wall009" geometry={nodes.Wall009.geometry} material={nodes.Wall009.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.009' }} />
        <mesh name="Wall010" geometry={nodes.Wall010.geometry} material={nodes.Wall010.material} position={[-2.083, 0, -4.496]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Wall.010' }} />
        <mesh name="Wall011" geometry={nodes.Wall011.geometry} material={nodes.Wall011.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.011' }} />
        <mesh name="Wall012" geometry={nodes.Wall012.geometry} material={nodes.Wall012.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.012' }} />
        <mesh name="Wall013" geometry={nodes.Wall013.geometry} material={nodes.Wall013.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.013' }} />
        <mesh name="Wall014" geometry={nodes.Wall014.geometry} material={nodes.Wall014.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.014' }} />
        <mesh name="Floor001" geometry={nodes.Floor001.geometry} material={materials['Material.001']} userData={{ name: 'Floor.001' }} />
        <mesh name="Wall015" geometry={nodes.Wall015.geometry} material={nodes.Wall015.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.015' }} />
        <mesh name="Wall016" geometry={nodes.Wall016.geometry} material={nodes.Wall016.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.016' }} />
        <mesh name="Wall017" geometry={nodes.Wall017.geometry} material={nodes.Wall017.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.017' }} />
        <mesh name="Wall018" geometry={nodes.Wall018.geometry} material={nodes.Wall018.material} position={[-2.083, 0, -4.496]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Wall.018' }} />
        <mesh name="Wall019" geometry={nodes.Wall019.geometry} material={nodes.Wall019.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.019' }} />
        <mesh name="Wall020" geometry={nodes.Wall020.geometry} material={nodes.Wall020.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.020' }} />
        <mesh name="Wall021" geometry={nodes.Wall021.geometry} material={nodes.Wall021.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.021' }} />
        <mesh name="Wall022" geometry={nodes.Wall022.geometry} material={nodes.Wall022.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.022' }} />
        <mesh name="Floor002" geometry={nodes.Floor002.geometry} material={materials['Material.001']} userData={{ name: 'Floor.002' }} />
        <mesh name="Wall023" geometry={nodes.Wall023.geometry} material={nodes.Wall023.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.023' }} />
        <mesh name="Wall024" geometry={nodes.Wall024.geometry} material={nodes.Wall024.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.024' }} />
        <mesh name="Wall025" geometry={nodes.Wall025.geometry} material={nodes.Wall025.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.025' }} />
        <mesh name="Wall026" geometry={nodes.Wall026.geometry} material={nodes.Wall026.material} position={[-2.083, 0, -4.496]} rotation={[0, -Math.PI / 2, 0]} userData={{ name: 'Wall.026' }} />
        <mesh name="Wall027" geometry={nodes.Wall027.geometry} material={nodes.Wall027.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.027' }} />
        <mesh name="Wall028" geometry={nodes.Wall028.geometry} material={nodes.Wall028.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.028' }} />
        <mesh name="Wall029" geometry={nodes.Wall029.geometry} material={nodes.Wall029.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.029' }} />
        <mesh name="Wall030" geometry={nodes.Wall030.geometry} material={nodes.Wall030.material} position={[-8.179, 0, 0.152]} rotation={[0, Math.PI / 2, 0]} userData={{ name: 'Wall.030' }} />
        <mesh name="Floor004" geometry={nodes.Floor004.geometry} material={materials['Material.001']} userData={{ name: 'Floor.004' }} />
        <mesh name="Wall031" geometry={nodes.Wall031.geometry} material={nodes.Wall031.material} position={[-8.179, 0, -4.496]} userData={{ name: 'Wall.031' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/warehousef1-front-mesh.glb')
